# Beispiele in NumPy

In [1]:
import numpy as np

In [3]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [7]:
a=np.arange(0,100,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [8]:
a=np.arange(0,100,5)
type(a)

numpy.ndarray

In [12]:
l1=[1,2,3,4,5,6,7,8,9,10]
type(l1)


list

In [13]:
l1=[1,2,3,4,5,6,7,8,9,10]
type(l1)
b=np.array(l1)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
l1=[1,2,3,4,5,6,7,8,9,10,"Hallo"]
type(l1)
b=np.array(l1)
type(b)
b

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Hallo'],
      dtype='<U21')

In [16]:
a.dtype

dtype('int64')

In [17]:
b.dtype

dtype('<U21')

In [18]:
#mehrdimensionale ndarrays

a2d=np.array([[1,2,3],[4,5,6]])
a2d



array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a2d=np.array([[1,2,3],[4,5,6]])

print(a2d)
print("Form: ",a2d.shape)
print("Anzahl der Elemente: ",a2d.size)

[[1 2 3]
 [4 5 6]]
Form:  (2, 3)
Anzahl der Elemente:  6


In [28]:
#zugriff auf Elemente

print(a)
print("Zweites Element: ",a[1])
print("Letztes Element: ",a[-1])
a[1:4] #Slicing

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
Zweites Element:  5
Letztes Element:  95


array([ 5, 10, 15])

In [34]:
print(a)
print("Zweites Element: ",a[1])
print("Letztes Element: ",a[-1])
print("---------------------------------------------------------------------------")
print("Anzeigen der ersten Liste: ",a2d[0])
print("Anzeigen des 2. Elementes der 2. Liste:",a2d[1,1])

print("---------------------------------------------------------------------------")

#Slicing
print("Elemente mit dem Index 1,2,3:",a[1:4])
print("Elemente ab dem Index 3: ",a[3:])
print("Elemente bis Index 10 :",a[:11])

print("Erste Liste 1 bis 2: ",a2d[1,0:1])

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
Zweites Element:  5
Letztes Element:  95
---------------------------------------------------------------------------
Anzeigen der ersten Liste:  [1 2 3]
Anzeigen des 2. Elementes der 2. Liste: 5
---------------------------------------------------------------------------
Elemente mit dem Index 1,2,3: [ 5 10 15]
Elemente ab dem Index 3:  [15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
Elemente bis Index 10 : [ 0  5 10 15 20 25 30 35 40 45 50]
Erste Liste 1 bis 2:  [4]


In [35]:
#Funktionen auf alle Elemente

a.sum() #Summe aller Zahlen in Array a

950